version: '1.0'
networks:
  roboshop:
    driver: bridge
services:
 web:
   image: web:v1
   container_name: web
   depends_on: 
   - catalogue
   - user
   ports:
   - 80:80
 catalogue:
   image: catalogue:v1
   container_name: catalogue
   depends_on:
   - mongodb
 mongodb:
   image: mongodb:v1
   container_name: mongodb
 user:
   image: user:v1
   container_name: user
   depends_on: 
   - mongodb
   - redis
 redis:
   image: redis
   
